# Generated by Django 6.0.4 on 2026-05-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"verbose_name": "cook", "verbose_name_plural": "cooks"},
        ),
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ("name",), "verbose_name_plural": "dishes"},
        ),
    ]
