# Generated by Django 6.0.4 on 2026-05-04 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_alter_cook_options_alter_dish_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="dishingredient",
            name="unit",
            field=models.CharField(default="g", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dishingredient",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_ingredients",
                to="kitchen.dish",
            ),
        ),
        migrations.AlterField(
            model_name="dishingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_ingredients",
                to="kitchen.ingredient",
            ),
        ),
    ]
