# Generated by Django 6.0.4 on 2026-05-12 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_dishingredient_unit_alter_dishingredient_dish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.PositiveSmallIntegerField(
                null=True, validators=[django.core.validators.MaxValueValidator(50)]
            ),
        ),
    ]
