# Generated by Django 6.0.4 on 2026-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0006_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "grams"),
                    ("kg", "kilograms"),
                    ("ml", "milliliters"),
                    ("pc", "pieces"),
                ],
                default="g",
                max_length=20,
            ),
        ),
    ]
